### ISSUE TITLE
лабораторная 04 - Андрей Рузаев курс  j110

### ISSUE THREAD

**Issue by barracuda78** [avalon-dev-j110/laboratornaya-rabota-no4-barracuda78#1]
@AlekseiMaslakov 
Алексей Павлович, добрый вечер.
Это Андрей Рузаев.
Сперва сделал коммит в master branch.
Откатил назад и залил в ветку.
Проверьте, пожалуйста!

**Comment by AlekseiMaslakov** [comment]
Здравствуйте, принято.
